package:
  image:
    name: gradle:jdk11@sha256:0fa50b624c362f81147294d61a9d0d198b17942bb3d50f5a2e7134616416e73f
  script:
    - gradle jar shadowjar
    - gradle -b legacy-build.gradle shadowjar
  artifacts:
    paths:
      - build/libs/keycloak-scim-1.0-SNAPSHOT.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all-legacy.jar
  only:
    - main
