package sh.libre.scim.integration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.tomakehurst.wiremock.client.ResponseDefinitionBuilder;
import com.github.tomakehurst.wiremock.extension.ResponseDefinitionTransformerV2;
import com.github.tomakehurst.wiremock.http.ResponseDefinition;
import com.github.tomakehurst.wiremock.stubbing.ServeEvent;

import java.util.UUID;

/**
 * WireMock response transformer that turns a SCIM {@code POST /Bulk} request into
 * a conformant {@code BulkResponse}. For every {@code Operations[]} entry in the
 * request body it emits a response op that echoes the request's {@code bulkId}
 * (the Keycloak-generated user id) with {@code status:201} and a freshly minted
 * resource {@code id} + {@code location}.
 *
 * <p>The kcUserIds are UUIDs generated by Keycloak at import time, so the response
 * cannot be a static stub body — it must be derived from the request, which is why
 * a transformer (rather than plain templating) is used here.
 *
 * <p>The {@code "id"} field is load-bearing: the SCIM SDK's
 * {@code BulkResponseOperation.getResourceId()} reads the RFC7643 {@code id}
 * attribute (not {@code location}), and the plugin only persists a SCIM mapping
 * when {@code getResourceId()} is present. {@code status} is emitted as a numeric
 * JSON integer to match the bulk-response schema (where {@code status} is typed
 * {@code integer}).
 */
public class ScimBulkResponseTransformer implements ResponseDefinitionTransformerV2 {

    static final String NAME = "scim-bulk";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    @Override
    public String getName() {
        return NAME;
    }

    @Override
    public boolean applyGlobally() {
        // Only apply to stubs that opt in via withTransformers(NAME).
        return false;
    }

    @Override
    public ResponseDefinition transform(ServeEvent serveEvent) {
        ResponseDefinition original = serveEvent.getResponseDefinition();
        String requestBody = serveEvent.getRequest().getBodyAsString();

        StringBuilder ops = new StringBuilder();
        try {
            JsonNode root = MAPPER.readTree(requestBody);
            JsonNode operations = root.get("Operations");
            if (operations != null && operations.isArray()) {
                for (int i = 0; i < operations.size(); i++) {
                    JsonNode op = operations.get(i);
                    JsonNode bulkIdNode = op.get("bulkId");
                    String bulkId = bulkIdNode == null ? null : bulkIdNode.asText();
                    String resourceId = UUID.randomUUID().toString();
                    if (ops.length() > 0) {
                        ops.append(",");
                    }
                    ops.append("""
                        {"method":"POST","bulkId":%s,"status":201,\
                        "id":"%s","location":"https://scim.example/Users/%s"}\
                        """.formatted(
                            bulkId == null ? "null" : MAPPER.writeValueAsString(bulkId),
                            resourceId,
                            resourceId));
                }
            }
        } catch (Exception e) {
            throw new IllegalStateException("failed to build SCIM bulk response from request body", e);
        }

        String body = """
            {"schemas":["urn:ietf:params:scim:api:messages:2.0:BulkResponse"],
             "Operations":[%s]}""".formatted(ops);

        return ResponseDefinitionBuilder.like(original).withBody(body).build();
    }
}
